vim.cmd(':set number')
vim.cmd(':set mouse=a')
vim.cmd(':set cursorline')
vim.cmd(':set noerrorbells')
vim.cmd(':set nowrap')
vim.cmd(':set smartcase')
vim.cmd(':set noswapfile')
vim.cmd(':set nobackup')
vim.cmd(':set undodir=~/.config/nvim/undo')
vim.cmd(':set undofile')
vim.cmd(':set incsearch')
vim.cmd(':set tabstop=2')
vim.cmd(':set softtabstop=0 noexpandtab')
vim.cmd(':set shiftwidth=2')
vim.cmd(':set colorcolumn=120')
vim.cmd(':set clipboard=unnamedplus')
vim.cmd(':set backspace=indent,eol,start')
vim.cmd('highlight ColorColumn ctermbg=0')
vim.cmd(':let mapleader=" "')
